name: "欢迎你"

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: "快到坑里来,小伙伴"
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "第一次参与,不错哦,让我们一起消除掉暴躁吧."
        pr-message: "开始消除暴躁了,干的不错,加油."
